---
- name: Run oscap report
  hosts: all
  become: yes

vars:
  oscap_profile: xccdf_org.ssgproject.content_profile_cis_server_l1
  oscap_policy: ssg-rhel8-ds

tasks:

- name: install openscap scanner
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - openscap-scanner
  - scap-security-guide

- block:
  - name: run openscap
    command: oscap xccdf eval --profile {{ oscap_profile }} --results-arf /tmp/oscap-arf.xml --report /tmp/oscap-report.html --fetch-remote-resources /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:
    - name: download report
      fetch:
        src: /tmp/oscap-report.html
        dest: ../oscap-reports/{{ inventory_hostname }}.html
        flat: yes
